config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :blogs do
    resources :likes, only: [:create, :destroy]
  end
  resources :mypage
  resources :users, only: [:show]
  root to: 'blogs#index'
get 'blogs/date/:date', to: 'blogs#table', as: 'blogs_table'
 # ← rootはどれか1つに決める
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_one_attached :image
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :blog
  belongs_to :user
  validates_uniqueness_of :blog_id, scope: :user_id
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :blogs, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_blogs, through: :likes, source: :blog
  validates :name, presence: true #追記

  def already_liked?(blog)
    self.likes.exists?(blog_id: blog.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

# deviseコントローラーにストロングパラメータを追加する          
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
before_action :authenticate_user!, only: [:new, :create] 
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def create
    blog = Blog.new(blog_params)

    blog.user_id = current_user.id
    
    if blog.save
      redirect_to action: "index"
    else
      redirect_to action: "new"
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, notice:"削除しました"
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "編集しました"
    else
      render 'edit'
    end
  end

 def table
  @date = Date.parse(params[:date])
  @blogs = Blog.where(start_time: @date.all_day)
 end
  private

  def blog_params
    params.require(:blog).permit(:title, :user_id, :content, :start_time, :image)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    like = current_user.likes.create(blog_id: params[:blog_id]) #user_idとblog_idの二つを代入
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(blog_id: params[:blog_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

# 追加箇所
  before_action :authenticate_user!, only: [:new, :create]
# ここまで

#追加箇所
    def index
        @tweets = Tweet.all
    end
  # ここまで
  
  #追加箇所
  def new
    @tweet = Tweet.new
  end

  def create
    tweet = Tweet.new(tweet_params)
    if tweet.save!
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body, :image)
  end
 #ここまで
def create
    tweet = Tweet.new(tweet_params)

    tweet.user_id = current_user.id  #追記

    if tweet.save
      redirect_to action: "index"
    else
      redirect_to action: "new"
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>

  <div class="title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

    <div class="time">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>
  
  <div class="content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>


  <div class="submit">
    <%= form.submit %>
  </div>

<% end %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>
<h1>カレンダー</h1>
<table>
  <thead>
    <tr>
      <th>場所</th>
      <th>時間</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
<%= month_calendar events: @blogs do |date, blogs| %>
  <%= link_to date.day, blogs_table_path(date: date), class: "calendar-day-link" %>
<div class="a">
  <% blogs.each do |blog| %>
    <div>
      <%= link_to blog.title, blog_path(blog) %>
    </div>
  <% end %>
</div>
<% end %>
<br>
<%= link_to '投稿する', new_blog_path %>


<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>

app/views/blogs/new.html.erb
<%= form_with(model: @blog, local: true) do |form| %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="title">
    <%= form.label :場所 %>
    <%= form.text_field :title %>
  </div>

    <div class="time">
    <%= form.label :行った日時 %>
    <%= form.datetime_select :start_time %>
  </div>
  
  <div class="content">
    <%= form.label :説明 %>
    <%= form.text_field :content %>
  </div>


  <div class="submit">
    <%= form.submit %>
  </div>

<% end %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>場所</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>画像</strong>
  <%= image_tag @blog.image.url, size: "400x300" if @blog.image.present? %>
</p>

<p>
  <strong>行った日時</strong>
  <%= @blog.start_time.strftime("%Y-%m-%d %H:%M") %>
</p>

<p>
  <strong>内容</strong>
  <%= @blog.content %>
</p>

    <%= @blog.user.name %> 
<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

<% if user_signed_in? %>
     <% if current_user.already_liked?(@blog) %>
        <%= link_to blog_like_path(id: @blog.id, blog_id: @blog.id), data: { turbo_method: :delete } do %>
            <p>いいねを取り消す</p><%= @blog.likes.count %>
        <% end %>
     <% else %>
        <%= link_to blog_likes_path(id: @blog.id, blog_id: @blog.id), data: { turbo_method: :post }  do %>
            <p>いいね</p><%= @blog.likes.count %>
        <% end %>
     <% end %>
<% else %>
    <p>いいねの数 = </p><%= @blog.likes.count %>
<% end %>

app/views/blogs/table.html.erb
<% if @blogs.present? %>
  <ul>
    <% @blogs.each do |blog| %>
      <li>
        <%= link_to blog_path(blog) do %>
          <%= blog.title %>【<%= blog.start_time.strftime("%H:%M") %>】
        <% end %>
      </li>
      <%= blog.user.name %>
      <p>画像</p>
      <% if blog.image.present? %>
        <%= image_tag blog.image.url, size: "250x200" %>
      <% end %>
      <p>場所</p>
      <%= blog.title %>
      <p>内容</p>
      <%= blog.content %>
        <% if user_signed_in? %>
     <% if current_user.already_liked?(blog) %>
        <%= link_to blog_like_path(id: blog.id, blog_id: blog.id), data: { turbo_method: :delete } do %>
            <p>いいねを取り消す</p><%= blog.likes.count %>
        <% end %>
     <% else %>
        <%= link_to blog_likes_path(id: blog.id, blog_id: blog.id), data: { turbo_method: :post }  do %>
            <p>いいね</p><%= blog.likes.count %>
        <% end %>
     <% end %>
    <% else %>
      <p>いいねの数 = </p><%= blog.likes.count %>
    <% end %>
    <% end %>
  </ul>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Travel" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

     <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


<body>
 <header>
  <h1>自然スポット</h1>
  <div class="header-list">
   <ul>
    <% if user_signed_in? %>
     <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
     <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>
 </header>
 <main>
  <%= yield %>
 </main>
</body>


</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tweets/index.html.erb
<h1>Geektravel</h1>
<h3>画像一覧</h3>
<%= link_to "新規投稿へ", new_tweet_path %>

<div class="tweets-container">
  <% if user_signed_in? %>
    <%= link_to "マイページへ", user_path(current_user.id) %>
  <% end %>
  <% @tweets.each do |t| %>

    <% if t.user.image.attached? %>
      <%= image_tag  t.user.image, size: '250x200'%>
    <% end %>
    <div class="tweet">

      <!-- 画像があれば表示 -->
      <%= image_tag t.image_url, size: "250x200" if t.image? %>

      <!-- ツイートの内容 -->
      <p><%= t.visit_date %></p>
      <p><%= t.body %></p>
      <p><%= t.user.email if t.user %></p>
      <p><%= t.created_at.strftime("%Y-%m-%d %H:%M") %></p>

  <% if user_signed_in? %>
    <% if current_user.already_liked?(t) %>
      <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
          <p>いいねを取り消す</p><%= t.likes.count %>
        <% end %>
      <% else %>
        <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
          <p>いいね</p><%= t.likes.count %>
        <% end %>
      <% end %>
  <% else %>
      <p>いいねの数 = </p><%= t.likes.count %>
  <% end %>

      <!-- リンク -->
      <%= link_to "詳細へ", tweet_path(t.id) %>
      <%= link_to "編集する", edit_tweet_path(t.id) %>
      <%= link_to "削除する", tweet_path(t.id), method: :delete %>
    </div>
  <% end %>
</div>

app/views/tweets/new.html.erb
<h1>Geektravel</h1>
<h3>新規tweet</h3>

<%= form_for @tweet, html: { multipart: true } do |f| %>

  <div class="field">
    <%= f.label :visit_date, "旅行日" %>
    <%= f.date_field :visit_date %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", tweets_path %>

app/views/tweets/show.html.erb
<h1>traveltwitter</h1>
<h3>Tweet詳細</h3>
<div class="tweet">rails user_signed_in
  <p><%= @tweet.body %></p>
  <p><%= @tweet.created_at %></p>
    <% if user_signed_in? %>
      <% if current_user.already_liked?(@tweet) %>
        <%= link_to tweet_like_path(@tweet), method: :delete do %>
          <p>いいねを取り消す</p><%= @tweet.likes.count %>
        <% end %>
      <% else %>
        <%= link_to tweet_likes_path(@tweet), method: :post do %>
          <p>いいね</p><%= @tweet.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <p>いいねの数 = </p><%= @tweet.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_tweet_path(@tweet.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @tweet.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<%= link_to "Tweet一覧に戻る", tweets_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.blogs.each do |t| %>
  <%= t.user.name %>
  <p>画像</p>
  <% if t.image.present? %>
    <%= image_tag t.image.url, size: "250x200" %>
  <% end %>
  <p>場所</p>
  <%= t.title %>
  <p>行った日時</p>
  <%= t.start_time %>
  <p>内容</p>
  <%= t.content %>
  
<% end %>
<!-- 以下はいいね機能を実装している場合-->
<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_blogs.each do |t| %>
  <%= t.user.name %>
  <p>画像</p>
  <% if t.image.present? %>
    <%= image_tag t.image.url, size: "250x200" %>
  <% end %>
  <p>場所</p>
  <%= t.title %>
  <p>行った日時</p>
  <%= t.start_time %>
  <p>内容</p>
  <%= t.content %>
<% end %>
<!-- ここまで-->

<%= link_to "Blog一覧に戻る", blogs_path %>